"""Add guest fields to tickets

Revision ID: 00232ed75fe8
Revises: 3dba1951fcd0
Create Date: 2026-03-11 22:04:40.241849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00232ed75fe8'
down_revision: Union[str, Sequence[str], None] = '3dba1951fcd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_messages', sa.Column('guest_sender', sa.String(), nullable=True))
    op.alter_column('ticket_messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tickets', sa.Column('guest_email', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('token', sa.String(), nullable=True))
    op.alter_column('tickets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_tickets_guest_email'), 'tickets', ['guest_email'], unique=False)
    op.create_index(op.f('ix_tickets_token'), 'tickets', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_token'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_guest_email'), table_name='tickets')
    op.alter_column('tickets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tickets', 'token')
    op.drop_column('tickets', 'guest_email')
    op.alter_column('ticket_messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ticket_messages', 'guest_sender')
    # ### end Alembic commands ###
